name: build

on:
  push:
    branches: [ "master" ]

jobs:
  build:

    runs-on: self-hosted

    steps:
    - name: build
      run: |
        source poky/oe-init-build-env auto_eth_build
        bitbake autoeth
      working-directory: /home/vm1/autoeth
     
        
      
