name: build

on:
  push:
    tags:
    - 'v*'

jobs:
  build:

    runs-on: self-hosted

    steps:
    - name: build
      run: |
        source poky/oe-init-build-env auto_eth_build
        bitbake autoeth
      working-directory: /home/vm1/autoeth
    - name: Upload Image
      uses: actions/upload-artifact@v3.1.0
      with:
        # Artifact name
        name: image.wic.bz2
        # A file, directory or wildcard pattern that describes what to upload
        path: /home/vm1/autoeth/auto_eth_build/tmp/deploy/images/raspberrypi4-64/autoeth-raspberrypi4-64.wic.bz2
    - name: Upload Image Bmap
      uses: actions/upload-artifact@v3.1.0
      with:
        # Artifact name
        name: image.wic.bmap
        # A file, directory or wildcard pattern that describes what to upload
        path: /home/vm1/autoeth/auto_eth_build/tmp/deploy/images/raspberrypi4-64/autoeth-raspberrypi4-64.wic.bmap
     
        
      
