name: build

on:
  push:
    branches: [ "master" ]

jobs:
  build:

    runs-on: self-hosted

    steps:
    - uses: actions/checkout@v3
    - name: clone poky
      uses: actions/checkout@v3
      with:
        repository: git://git.yoctoproject.org/poky
        ref: honister
    - name: clone meta-openembedded
      uses: actions/checkout@v3
      with:
        repository: https://github.com/openembedded/meta-openembedded
        ref: honister
    - name: clone meta-raspberrypi
      uses: actions/checkout@v3
      with:
        repository: https://github.com/agherzan/meta-raspberrypi
        ref: honister
        
      
